---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - ps aux
- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
