---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - ps aux
- name: notify
  image: plugins/slack
  settings:
    from_secret: slack-secret
  channel: test-channel
