---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - ps aux
- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    recipient: Adam Toy
