---
kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - ps aux

notify:
    image: plugins/slack
    webhook_url: https://hooks.slack.com/services/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
    channel: test-channel
